image: alpine/edge
secrets:
  - a60a3df4-1aeb-4663-b816-b7425fe69399
sources:
  - git@git.sr.ht/~igna/shiro.rest
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      echo 'cd shiro.rest' >> ~/.buildenv
  - mirror: |
      git push --force --mirror git@github.com:ignaigna/shiro.rest.git
