services:
  web:
    container_name: web
    hostname: web.shiro.local
    build: .
    restart: always
    expose:
      - 3000
    networks:
      - shiro
    env_file:
      - .env

networks:
  shiro:
    external: true
